name: documentation
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'resources/**'
      - 'tools/**'
  pull_request:
    paths:
      - 'docs/**'
      - 'resources/**'
      - 'tools/**'
jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Run website_build.sh
        # Use a conditional step instead of a conditional job to work around #20700.
        if: github.repository == 'web-platform-tests/wpt'
        run: ./tools/ci/website_build.sh
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
